import app.core.config as _cfg

BASE_URL = _cfg.COGITX_BASE_URL
EXPORT_ID = _cfg.COGITX_EXPORT_ID
EMAIL_EXPORT_ID = _cfg.COGITX_EMAIL_EXPORT_ID
EMAIL_CLIENT_ID = _cfg.COGITX_EMAIL_CLIENT_ID
EMAIL_CLIENT_SECRET = _cfg.COGITX_EMAIL_CLIENT_SECRET
INGEST_EXPORT_ID = _cfg.COGITX_INGEST_EXPORT_ID
INGEST_CLIENT_ID = _cfg.COGITX_INGEST_CLIENT_ID
INGEST_CLIENT_SECRET = _cfg.COGITX_INGEST_CLIENT_SECRET
CLIENT_ID = _cfg.COGITX_CLIENT_ID
CLIENT_SECRET = _cfg.COGITX_CLIENT_SECRET
POLL_INTERVAL = _cfg.COGITX_POLL_INTERVAL
POLL_TIMEOUT = _cfg.COGITX_POLL_TIMEOUT
